In [11]:
# Importing the appropriate libraries
import sklearn # Modelling
import pandas as pd # tables
import datetime
from sklearn import preprocessing
from sklearn.model_selection import train_test_split # Splitting testing training
from sklearn.neural_network import MLPClassifier

In [2]:
# Read in the raw data
shoppingTable = pd.read_csv("juneShopping.csv")

In [45]:
# Data pre-processing

# Keep only the date and the description
shoppingTable['created'] = pd.to_datetime(shoppingTable['created'])
shoppingTable['day_of_week'] = shoppingTable['created'].dt.weekday
X = shoppingTable['day_of_week']
Y = shoppingTable.filter(items=['description'])

YUnique = Y['description'].unique()

#le = preprocessing.LabelEncoder()
Y["description"] = Y["description"].astype('category')

# Decode table

Y["catcodes"] = Y["description"].cat.codes

Y
#le.fit_transform(Y['description'].values)
#le.fit(YUnique.values)
#le.transform(["Sainsbury's"])
#days = {0:'Waitrose',1:'Tesco',2:'Sainsbury\'s',3:'Friends House',4:'Poundland',5:'McDonald\'s',6:'Tesco'}

                    description  catcodes
0                      Waitrose        18
1                         Tesco        16
2                   Sainsbury's        15
3                 Friends House         6
4                 Friends House         6
5                     Poundland        13
6                   Sainsbury's        15
7                   Sainsbury's        15
8                    McDonald's        10
9                         Tesco        16
10                        Tesco        16
11         Transport for London        17
12                       Wasabi        19
13         Transport for London        17
14                        Tesco        16
15                  Sainsbury's        15
16                          NaN        -1
17                 Franco Manca         5
18              Marks & Spencer         9
19                   Barburrito         0
20                        Tesco        16
21                        Tesco        16
22                   McDonald's        10
23                 College Cafe         3
24                   Costcutter         4
25                       Wasabi        19
26                  Sainsbury's        15
27                        Tesco        16
28                        Boots         1
29              Chicken Cottage         2
..                          ...       ...
77                        Tesco        16
78                 College Cafe         3
79                        Tesco        16
80                        Boots         1
81                  Sainsbury's        15
82                  Sainsbury's        15
83                  Sainsbury's        15
84                        Tesco        16
85                   McDonald's        10
86   Payment from Dávid Pásztúr        12
87                Myprotein.com        11
88                       Wasabi        19
89                        Tesco        16
90                  Sainsbury's        15
91                        Tesco        16
92                          NaN        -1
93                 College Cafe         3
94                  Sainsbury's        15
95                 College Cafe         3
96                 College Cafe         3
97                 College Cafe         3
98         Transport for London        17
99                   McDonald's        10
100                College Cafe         3
101             Chicken Cottage         2
102                       Tesco        16
103        Transport for London        17
104        Transport for London        17
105                 Sainsbury's        15
106                      Wasabi        19

[107 rows x 2 columns]

In [53]:
# Partition the dataset
X_train, X_test, y_train, y_test = \
        train_test_split(X, Y["catcodes"], test_size=.4, random_state=42)

In [63]:
clf = MLPClassifier();
clf.fit(X_train.to_frame(),y_train.to_frame())
score = clf.score(X_test.to_frame(), y_test.to_frame())

score
clf.predict(5)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:904: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)

array([15], dtype=int8)